#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3.7'

volumes:
  couchdb0.ecommerce:
  couchdb1.ecommerce:
  couchdb0.seller:
  couchdb1.seller:
  couchdb0.shipper:
  couchdb1.shipper:

networks:
  fabric_network: # <-- Đổi tên từ 'test'
    name: fabric_ecommerce_network

services:
  # ===================================================================
  # CÁC CONTAINER COUCHDB (6 INSTANCES)
  # ===================================================================
  couchdb0.ecommerce:
    container_name: couchdb0.ecommerce
    image: couchdb:3.1.1 # Bạn có thể đổi 3.1.1 thành 3.4.2 nếu muốn
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984" # Port của Peer 0 - Org ECommerce
    networks:
      - fabric_network

  couchdb1.ecommerce:
    container_name: couchdb1.ecommerce
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5985:5984" # Port của Peer 1 - Org ECommerce
    networks:
      - fabric_network

  couchdb0.seller:
    container_name: couchdb0.seller
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984" # Port của Peer 0 - Org Seller
    networks:
      - fabric_network

  couchdb1.seller:
    container_name: couchdb1.seller
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7985:5984" # Port của Peer 1 - Org Seller
    networks:
      - fabric_network

  couchdb0.shipper:
    container_name: couchdb0.shipper
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9984:5984" # Port của Peer 0 - Org Shipper
    networks:
      - fabric_network

  couchdb1.shipper:
    container_name: couchdb1.shipper
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9985:5984" # Port của Peer 1 - Org Shipper
    networks:
      - fabric_network

  # ===================================================================
  # TIÊM CẤU HÌNH COUCHDB VÀO CÁC PEER
  # ===================================================================
  peer0.ecommerce.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.ecommerce:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb0.ecommerce

  peer1.ecommerce.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.ecommerce:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb1.ecommerce

  peer0.seller.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.seller:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb0.seller

  peer1.seller.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.seller:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb1.seller

  peer0.shipper.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.shipper:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb0.shipper

  peer1.shipper.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.shipper:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb1.shipper
